print("=== OOP CONCEPTS QUIZ ===")
print("")
print("1. What is a Class?")
print("   Answer: A blueprint for creating objects, defining attributes and methods.")
print("")
print("2. What is an Instance?")
print("   Answer: A specific object created from a class.")
print("")
print("3. What is Encapsulation?")
print("   Answer: Bundling data and methods that operate on that data within a class, restricting direct access.")
print("")
print("4. What is Abstraction?")
print("   Answer: Hiding complex implementation details and exposing only essential features.")
print("")
print("5. What is Inheritance?")
print("   Answer: Allowing a class to inherit attributes and methods from another class.")
print("")
print("6. What is Multiple Inheritance?")
print("   Answer: A class inheriting from more than one parent class.")
print("")
print("7. What is Polymorphism?")
print("   Answer: The ability to use a common interface for different underlying forms.")
print("")
print("8. What is Method Resolution Order or MRO?")
print("   Answer: The order in which Python searches for methods in a hierarchy of classes.")